# Generated by Django 6.0.4 on 2026-04-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0002_formation_updated_at_alter_cart_id_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-created_at']},
        ),
    ]
