# Generated by Django 6.0.4 on 2026-09-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0003_alter_formation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='duration',
            field=models.CharField(blank=True, help_text='Ex : 4 semaines, 12h de vidéo', max_length=60),
        ),
        migrations.AddField(
            model_name='formation',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formation',
            name='level',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20),
        ),
        migrations.AddField(
            model_name='formation',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancien prix (avant réduction). Laisser vide si pas de promotion.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='students_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'inscrits"),
        ),
        migrations.AddField(
            model_name='formation',
            name='what_you_learn',
            field=models.TextField(blank=True, help_text='Un point par ligne.', verbose_name='Ce que vous allez apprendre'),
        ),
    ]
