# Generated by Django 6.0.4 on 2026-09-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0004_formation_duration_formation_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='file',
            field=models.FileField(blank=True, help_text='PDF, Word ou Excel — accessible uniquement après paiement confirmé (type « Formation numérique »).', null=True, upload_to='formations/fichiers/', verbose_name='Fichier à télécharger'),
        ),
        migrations.AddField(
            model_name='formation',
            name='formation_type',
            field=models.CharField(choices=[('cours', 'Formation payante en ligne (panier + WhatsApp)'), ('inscription', 'Inscription par formulaire (groupe WhatsApp)'), ('numerique', 'Formation numérique à télécharger (PDF / Word / Excel)')], default='cours', max_length=20, verbose_name='Type de formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, help_text='Envoyé par email après inscription (type « Inscription par formulaire »).', verbose_name='Lien du groupe WhatsApp'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('whatsapp_country_code', models.CharField(default='+228', max_length=6, verbose_name='Indicatif')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='Numéro WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('motivation', models.TextField(blank=True, verbose_name='Message de motivation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Formations.formation')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
