# Generated by Django 6.0.4 on 2026-09-17 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0006_alter_cart_created_at_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL)')),
                ('icon', models.CharField(blank=True, help_text='Classe Font Awesome ex: fa-code', max_length=60, verbose_name='Icône')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie de formation',
                'verbose_name_plural': 'Catégories de formation',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='Formations.formationcategory', verbose_name='Catégorie'),
        ),
    ]
