# Generated by Django 6.0.4 on 2026-09-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0007_formationcategory_formation_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Article du panier', 'verbose_name_plural': 'Articles du panier'},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Commande formation', 'verbose_name_plural': 'Commandes formation'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Article de la commande', 'verbose_name_plural': 'Articles de la commande'},
        ),
    ]
