# Generated by Django 6.0.4 on 2026-09-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('client', models.CharField(blank=True, max_length=150, verbose_name='Client')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies', models.CharField(blank=True, help_text='Séparées par des virgules, ex : Django, React, PostgreSQL', max_length=255)),
                ('link', models.URLField(blank=True, verbose_name='Lien vers le projet')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('role', models.CharField(max_length=150, verbose_name='Rôle')),
                ('bio', models.TextField(blank=True, verbose_name='À propos')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('technologies', models.CharField(blank=True, help_text='Séparées par des virgules, ex : Python, Django, Photoshop', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Numéro ex: 22890000000', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_founder', models.BooleanField(default=False, verbose_name='Fondateur')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
