# Generated by Django 6.0.4 on 2026-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Ex : Formations, E-Commerce', max_length=80, verbose_name='Étiquette')),
                ('title', models.CharField(help_text="Vous pouvez mettre un mot en évidence (doré) en l'entourant de <em>...</em>", max_length=255, verbose_name='Titre')),
                ('subtitle', models.TextField(blank=True, verbose_name='Sous-titre')),
                ('image', models.ImageField(upload_to='hero_slides/', verbose_name='Image de fond')),
                ('link_url', models.CharField(help_text='Ex : /boutique/ ou https://...', max_length=255, verbose_name='Lien')),
                ('link_text', models.CharField(default='En savoir plus', max_length=80, verbose_name='Texte du bouton')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Slide du carrousel',
                'verbose_name_plural': 'Slides du carrousel',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsTickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex : Nouveau, Boutique, Article', max_length=40, verbose_name='Étiquette')),
                ('message', models.CharField(max_length=150, verbose_name='Message')),
                ('link_url', models.CharField(help_text='Ex : /formations/ ou https://...', max_length=255, verbose_name='Lien')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Actualité (bandeau)',
                'verbose_name_plural': 'Actualités (bandeau)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
