# Generated by Django 6.0.4 on 2026-09-14 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_hero_and_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Classe Font Awesome ex: fa-handshake', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie de partenaire',
                'verbose_name_plural': 'Catégories de partenaires',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='partner',
            name='achievements',
            field=models.TextField(blank=True, help_text='Ce que vous avez accompli ensemble avec ce partenaire.', verbose_name='Réalisations'),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.CharField(blank=True, help_text="Ex : Togo, International, Côte d'Ivoire", max_length=100, verbose_name='Pays / Localisation'),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='domain',
            field=models.CharField(blank=True, help_text='Ex : Financement de projets numériques, Éducation', max_length=200, verbose_name="Domaine d'intervention"),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='partner',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Numéro complet ex : 22890000000', max_length=30, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='core.partnercategory', verbose_name='Catégorie'),
        ),
    ]
