# Generated by Django 6.0.4 on 2026-09-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_partnercategory_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('whatsapp', models.CharField(help_text='Numéro complet, ex : 22890000000', max_length=30, verbose_name='Numéro WhatsApp')),
                ('country', models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Afrique du Sud', 'Afrique du Sud'), ('Albanie', 'Albanie'), ('Algérie', 'Algérie'), ('Allemagne', 'Allemagne'), ('Andorre', 'Andorre'), ('Angola', 'Angola'), ('Antigua-et-Barbuda', 'Antigua-et-Barbuda'), ('Arabie saoudite', 'Arabie saoudite'), ('Argentine', 'Argentine'), ('Arménie', 'Arménie'), ('Australie', 'Australie'), ('Autriche', 'Autriche'), ('Azerbaïdjan', 'Azerbaïdjan'), ('Bahamas', 'Bahamas'), ('Bahreïn', 'Bahreïn'), ('Bangladesh', 'Bangladesh'), ('Barbade', 'Barbade'), ('Belgique', 'Belgique'), ('Belize', 'Belize'), ('Bénin', 'Bénin'), ('Bhoutan', 'Bhoutan'), ('Biélorussie', 'Biélorussie'), ('Birmanie (Myanmar)', 'Birmanie (Myanmar)'), ('Bolivie', 'Bolivie'), ('Bosnie-Herzégovine', 'Bosnie-Herzégovine'), ('Botswana', 'Botswana'), ('Brésil', 'Brésil'), ('Brunei', 'Brunei'), ('Bulgarie', 'Bulgarie'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cambodge', 'Cambodge'), ('Cameroun', 'Cameroun'), ('Canada', 'Canada'), ('Cap-Vert', 'Cap-Vert'), ('République centrafricaine', 'République centrafricaine'), ('Chili', 'Chili'), ('Chine', 'Chine'), ('Chypre', 'Chypre'), ('Colombie', 'Colombie'), ('Comores', 'Comores'), ('Congo-Brazzaville', 'Congo-Brazzaville'), ('RD Congo (Kinshasa)', 'RD Congo (Kinshasa)'), ('Corée du Nord', 'Corée du Nord'), ('Corée du Sud', 'Corée du Sud'), ('Costa Rica', 'Costa Rica'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Croatie', 'Croatie'), ('Cuba', 'Cuba'), ('Danemark', 'Danemark'), ('Djibouti', 'Djibouti'), ('Dominique', 'Dominique'), ('Égypte', 'Égypte'), ('Émirats arabes unis', 'Émirats arabes unis'), ('Équateur', 'Équateur'), ('Érythrée', 'Érythrée'), ('Espagne', 'Espagne'), ('Estonie', 'Estonie'), ('Eswatini', 'Eswatini'), ('États-Unis', 'États-Unis'), ('Éthiopie', 'Éthiopie'), ('Fidji', 'Fidji'), ('Finlande', 'Finlande'), ('France', 'France'), ('Gabon', 'Gabon'), ('Gambie', 'Gambie'), ('Géorgie', 'Géorgie'), ('Ghana', 'Ghana'), ('Grèce', 'Grèce'), ('Grenade', 'Grenade'), ('Guatemala', 'Guatemala'), ('Guinée', 'Guinée'), ('Guinée-Bissau', 'Guinée-Bissau'), ('Guinée équatoriale', 'Guinée équatoriale'), ('Guyana', 'Guyana'), ('Haïti', 'Haïti'), ('Honduras', 'Honduras'), ('Hongrie', 'Hongrie'), ('Îles Marshall', 'Îles Marshall'), ('Îles Salomon', 'Îles Salomon'), ('Inde', 'Inde'), ('Indonésie', 'Indonésie'), ('Irak', 'Irak'), ('Iran', 'Iran'), ('Irlande', 'Irlande'), ('Islande', 'Islande'), ('Israël', 'Israël'), ('Italie', 'Italie'), ('Jamaïque', 'Jamaïque'), ('Japon', 'Japon'), ('Jordanie', 'Jordanie'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kirghizistan', 'Kirghizistan'), ('Kiribati', 'Kiribati'), ('Kosovo', 'Kosovo'), ('Koweït', 'Koweït'), ('Laos', 'Laos'), ('Lesotho', 'Lesotho'), ('Lettonie', 'Lettonie'), ('Liban', 'Liban'), ('Liberia', 'Liberia'), ('Libye', 'Libye'), ('Liechtenstein', 'Liechtenstein'), ('Lituanie', 'Lituanie'), ('Luxembourg', 'Luxembourg'), ('Macédoine du Nord', 'Macédoine du Nord'), ('Madagascar', 'Madagascar'), ('Malaisie', 'Malaisie'), ('Malawi', 'Malawi'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malte', 'Malte'), ('Maroc', 'Maroc'), ('Maurice', 'Maurice'), ('Mauritanie', 'Mauritanie'), ('Mexique', 'Mexique'), ('Micronésie', 'Micronésie'), ('Moldavie', 'Moldavie'), ('Monaco', 'Monaco'), ('Mongolie', 'Mongolie'), ('Monténégro', 'Monténégro'), ('Mozambique', 'Mozambique'), ('Namibie', 'Namibie'), ('Nauru', 'Nauru'), ('Népal', 'Népal'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Norvège', 'Norvège'), ('Nouvelle-Zélande', 'Nouvelle-Zélande'), ('Oman', 'Oman'), ('Ouganda', 'Ouganda'), ('Ouzbékistan', 'Ouzbékistan'), ('Pakistan', 'Pakistan'), ('Palaos', 'Palaos'), ('Palestine', 'Palestine'), ('Panama', 'Panama'), ('Papouasie-Nouvelle-Guinée', 'Papouasie-Nouvelle-Guinée'), ('Paraguay', 'Paraguay'), ('Pays-Bas', 'Pays-Bas'), ('Pérou', 'Pérou'), ('Philippines', 'Philippines'), ('Pologne', 'Pologne'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('Roumanie', 'Roumanie'), ('Royaume-Uni', 'Royaume-Uni'), ('Russie', 'Russie'), ('Rwanda', 'Rwanda'), ('Saint-Christophe-et-Niévès', 'Saint-Christophe-et-Niévès'), ('Saint-Marin', 'Saint-Marin'), ('Saint-Vincent-et-les-Grenadines', 'Saint-Vincent-et-les-Grenadines'), ('Sainte-Lucie', 'Sainte-Lucie'), ('Salvador', 'Salvador'), ('Samoa', 'Samoa'), ('São Tomé-et-Principe', 'São Tomé-et-Principe'), ('Sénégal', 'Sénégal'), ('Serbie', 'Serbie'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Singapour', 'Singapour'), ('Slovaquie', 'Slovaquie'), ('Slovénie', 'Slovénie'), ('Somalie', 'Somalie'), ('Soudan', 'Soudan'), ('Soudan du Sud', 'Soudan du Sud'), ('Sri Lanka', 'Sri Lanka'), ('Suède', 'Suède'), ('Suisse', 'Suisse'), ('Suriname', 'Suriname'), ('Syrie', 'Syrie'), ('Tadjikistan', 'Tadjikistan'), ('Tanzanie', 'Tanzanie'), ('Tchad', 'Tchad'), ('Tchéquie', 'Tchéquie'), ('Thaïlande', 'Thaïlande'), ('Timor oriental', 'Timor oriental'), ('Togo', 'Togo'), ('Tonga', 'Tonga'), ('Trinité-et-Tobago', 'Trinité-et-Tobago'), ('Tunisie', 'Tunisie'), ('Turkménistan', 'Turkménistan'), ('Turquie', 'Turquie'), ('Tuvalu', 'Tuvalu'), ('Ukraine', 'Ukraine'), ('Uruguay', 'Uruguay'), ('Vanuatu', 'Vanuatu'), ('Vatican', 'Vatican'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam'), ('Yémen', 'Yémen'), ('Zambie', 'Zambie'), ('Zimbabwe', 'Zimbabwe'), ('Autre', 'Autre')], max_length=100, verbose_name='Pays')),
                ('phone_code', models.CharField(default='+228', max_length=6, verbose_name='Indicatif')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('logo', models.ImageField(upload_to='partner_applications/', verbose_name='Logo')),
                ('description', models.TextField(verbose_name='Présentation / description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Acceptée — publiée'), ('rejected', 'Rejetée')], default='pending', max_length=10, verbose_name='Statut')),
                ('admin_note', models.TextField(blank=True, verbose_name='Note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='core.partner', verbose_name='Partenaire publié')),
            ],
            options={
                'verbose_name': 'Candidature de partenariat',
                'verbose_name_plural': 'Candidatures de partenariat',
                'ordering': ['-created_at'],
            },
        ),
    ]
