# Generated by Django 6.0.4 on 2026-09-14 23:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partnerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapplication',
            name='logo',
            field=models.ImageField(upload_to='partner_applications/', validators=[core.models.validate_max_upload_size], verbose_name='Logo'),
        ),
    ]
