# Generated by Django 6.0.4 on 2026-09-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_heroslide_order_alter_newstickeritem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('whatsapp_1', models.CharField(blank=True, help_text='Numéro complet ex : 22890000000', max_length=20, verbose_name='WhatsApp (1)')),
                ('whatsapp_2', models.CharField(blank=True, help_text='Numéro complet ex : 22890000000 (laisser vide si un seul numéro)', max_length=20, verbose_name='WhatsApp (2)')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Lien Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Lien Instagram')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='Lien TikTok')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Lien YouTube')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Lien Telegram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Lien X (Twitter)')),
            ],
            options={
                'verbose_name': 'Réglages du site',
                'verbose_name_plural': 'Réglages du site',
            },
        ),
    ]
