# Generated by Django 6.0.4 on 2026-09-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de l'événement"),
        ),
        migrations.AddField(
            model_name='publication',
            name='event_location',
            field=models.CharField(blank=True, max_length=200, verbose_name="Lieu de l'événement"),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('article', 'Article / Actualité'), ('evenement', 'Événement (avec inscription possible)')], default='article', max_length=20, verbose_name='Type de publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='registration_open',
            field=models.BooleanField(default=True, help_text="Décochez pour fermer les inscriptions sans dépublier l'article.", verbose_name='Inscriptions ouvertes'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone / WhatsApp')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('message', models.TextField(blank=True, verbose_name='Message (optionnel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(limit_choices_to={'publication_type': 'evenement'}, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Publications.publication')),
            ],
            options={
                'verbose_name': 'Inscription à un événement',
                'verbose_name_plural': 'Inscriptions aux événements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='publications/gallery-videos/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Publications.publication')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
