# Generated by Django 6.0.4 on 2026-09-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0002_publication_event_date_publication_event_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='message',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='phone',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='phone_code',
            field=models.CharField(default='+228', max_length=6, verbose_name='Indicatif'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='phone_number',
            field=models.CharField(default='', max_length=30, verbose_name='Numéro WhatsApp'),
        ),
        migrations.AddField(
            model_name='publication',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text="Passé cette date, le formulaire d'inscription n'est plus accessible (laisser vide pour ne pas fixer de limite).", null=True, verbose_name="Date limite d'inscription"),
        ),
        migrations.AlterField(
            model_name='publication',
            name='registration_open',
            field=models.BooleanField(default=True, help_text="Décochez si cet événement ne propose pas d'inscription (ex : simple annonce) — le bouton d'inscription n'apparaîtra pas.", verbose_name="Formulaire d'inscription activé"),
        ),
    ]
