# Generated by Django 6.0.4 on 2026-09-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0003_remove_eventregistration_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='publication',
            field=models.ForeignKey(limit_choices_to={'publication_type': 'evenement'}, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Publications.publication', verbose_name='Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='Publications.publicationcategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='publicationcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='publicationcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Classe Font Awesome ex: fa-heartbeat', max_length=60, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='publicationcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='publicationcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='publicationcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='image',
            field=models.ImageField(upload_to='publications/gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Publications.publication', verbose_name='Publication'),
        ),
        migrations.AlterField(
            model_name='publicationvideo',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='publicationvideo',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Publications.publication', verbose_name='Publication'),
        ),
        migrations.AlterField(
            model_name='publicationvideo',
            name='video',
            field=models.FileField(upload_to='publications/gallery-videos/', verbose_name='Vidéo'),
        ),
    ]
