# Generated by Django 6.0.4 on 2026-09-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0004_alter_eventregistration_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='document',
            field=models.FileField(blank=True, help_text='Optionnel — affiche un bouton de téléchargement sur la publication.', null=True, upload_to='publications/documents/', verbose_name='Document à télécharger (PDF, Word...)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='document_label',
            field=models.CharField(blank=True, help_text='Ex : « Télécharger la liste des candidats admis ». Laisser vide pour un texte par défaut.', max_length=100, verbose_name='Texte du bouton de téléchargement'),
        ),
    ]
