# Generated by Django 6.0.4 on 2026-09-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0005_publication_document_publication_document_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationimage',
            options={'ordering': ['order'], 'verbose_name': 'Image de la publication', 'verbose_name_plural': 'Images de la publication'},
        ),
        migrations.AlterModelOptions(
            name='publicationvideo',
            options={'ordering': ['order'], 'verbose_name': 'Vidéo de la publication', 'verbose_name_plural': 'Vidéos de la publication'},
        ),
    ]
