# Generated by Django 6.0.4 on 2026-09-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Classe Font Awesome ex: fa-desktop (sinon, icône de la catégorie)', max_length=60),
        ),
    ]
