# Generated by Django 6.0.4 on 2026-09-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_service_category_alter_service_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Catégorie de service', 'verbose_name_plural': 'Catégories de service'},
        ),
        migrations.AlterModelOptions(
            name='servicecontact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de contact', 'verbose_name_plural': 'Demandes de contact'},
        ),
    ]
