# Generated by Django 6.0.4 on 2026-04-24 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
