# Generated by Django 6.0.4 on 2026-09-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_passwordresetcode_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'verbose_name': 'Code de réinitialisation du mot de passe', 'verbose_name_plural': 'Codes de réinitialisation du mot de passe'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
