# Generated by Django 6.0.4 on 2026-04-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='cash_delivery_message',
            field=models.TextField(blank=True, null=True, verbose_name='Message pour la livraison'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='cash_delivery_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom pour la livraison'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='cash_delivery_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone pour la livraison'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('cash_on_delivery', 'Paiement en espèces à la livraison'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
