# Generated by Django 6.0.4 on 2026-09-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Ancien prix (avant réduction). Laisser vide si le produit n'est pas en promotion.", max_digits=10, null=True),
        ),
    ]
