# Generated by Django 6.0.4 on 2026-09-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_product_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Vous êtes une entreprise ou un fournisseur ? Contactez-nous pour une collaboration et proposez vos produits sur notre boutique.', max_length=300, verbose_name='Message')),
                ('whatsapp_number', models.CharField(default='22890000000', help_text='Numéro complet, ex : 22890000000', max_length=30, verbose_name='Numéro WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Bandeau collaboration',
                'verbose_name_plural': 'Bandeau collaboration',
            },
        ),
    ]
