# Generated by Django 6.0.4 on 2026-09-17 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_collabbanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Classe Font Awesome ex: fa-mobile', max_length=50, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bulk_min_qty',
            field=models.PositiveIntegerField(default=10, help_text='Quantité min pour prix en gros', verbose_name='Quantité min. (prix en gros)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix en gros', max_digits=10, null=True, verbose_name='Prix en gros'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Shop.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/products/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Ancien prix (avant réduction). Laisser vide si le produit n'est pas en promotion.", max_digits=10, null=True, verbose_name='Ancien prix'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='shop/videos/', verbose_name='Vidéo'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='shop/products/gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Shop.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Shop.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Shop.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_cart', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='shopcartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Shop.shopcart', verbose_name='Panier'),
        ),
        migrations.AlterField(
            model_name='shopcartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='shopcartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='payment_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('flooz', 'Flooz'), ('tmoney', 'T-Money'), ('wave', 'Wave'), ('cash', 'Espèces')], default='cash', max_length=20, verbose_name='Moyen de paiement'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de reçu'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('cash_on_delivery', 'Paiement en espèces à la livraison'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='shoporderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Shop.shoporder', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='shoporderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='shoporderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='shoporderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
    ]
