# Generated by Django 6.0.4 on 2026-09-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='collabbanner',
            options={'verbose_name': 'Bannière de collaboration', 'verbose_name_plural': 'Bannières de collaboration'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'Image du produit', 'verbose_name_plural': 'Images du produit'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avis client', 'verbose_name_plural': 'Avis clients'},
        ),
        migrations.AlterModelOptions(
            name='shopcart',
            options={'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterModelOptions(
            name='shopcartitem',
            options={'verbose_name': 'Article du panier', 'verbose_name_plural': 'Articles du panier'},
        ),
        migrations.AlterModelOptions(
            name='shoporder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commande boutique', 'verbose_name_plural': 'Commandes boutique'},
        ),
        migrations.AlterModelOptions(
            name='shoporderitem',
            options={'verbose_name': 'Article de la commande', 'verbose_name_plural': 'Articles de la commande'},
        ),
    ]
