# Generated by Django 6.0.4 on 2026-09-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_announcement_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_whatsapp',
            field=models.CharField(blank=True, help_text='Optionnel — utilisé à la place du numéro WhatsApp par défaut du site pour le bouton "Commander via WhatsApp" de ce produit. Utile quand le produit est revendu pour le compte d\'un tiers (ex : un autre commerçant, un revendeur) et que les commandes doivent lui arriver directement. Format : 22890000000.', max_length=30, verbose_name='Numéro WhatsApp de contact (spécifique)'),
        ),
    ]
